# Generated by Django 3.1.3 on 2021-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(related_name='order', to='core.Good'),
        ),
    ]
