# Generated by Django 3.1.5 on 2021-02-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
    ]
